"""add posts model

Revision ID: 21fcd605f393
Revises: c7fb19d56c48
Create Date: 2017-01-03 10:35:37.685495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fcd605f393'
down_revision = 'c7fb19d56c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FDM_machines',
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('x_size', sa.Integer(), nullable=True),
    sa.Column('y_size', sa.Integer(), nullable=True),
    sa.Column('z_size', sa.Integer(), nullable=True),
    sa.Column('material', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ip_address')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.add_column(u'tasks', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tasks', 'priority')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('FDM_machines')
    # ### end Alembic commands ###
